[package]
name = "audioswitcher"
version = "0.1.0"
edition = "2024"

[dependencies]
inquire = "0.9.1"
windows = {version ="0.61", features = ["Win32_Media_MediaFoundation","Win32_System_Com", "Win32_Media_Audio","Win32_UI_Shell_PropertiesSystem", "Win32_System_Variant", "Win32_System_Com_StructuredStorage","Win32_Devices_FunctionDiscovery" ] }
com-policy-config = "0.6.0"
clap = { version = "4.5", features = ["derive"] }
log = "0.4.28"
env_logger = "0.11.8"
serde_json = "1.0.145"
directories = {version = "6.0"}
tempfile = "3.23.0"